# This is a basic workflow to help you get started with Actions

name: pdfLaTeX compile the homework questions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: >-
      github.event.repository.html_url == 'https://github.com/BrownCSCI1430/Homework0_Tutorial_Template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: Homework0_Template.tex
          working_directory: . # optional
          compiler: latexmk # optional, default is latexmk
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Commit and Push PDF
        run: |
          touch Homework0_Template.pdf
          git add Homework0_Template.pdf
          git config --local user.name 'automated-github-action'
          git config --local user.email 'cs1430-github-actions[bot]@users.noreply.github.com'
          git commit -m "Compile written PDF"
          git push
